/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Exposes the `encode_rs` function to Node.js via N-API. */
export declare function encode(image: string, message: string, step: string, output: string): Promise<void>
/** Exposes the `decode_rs` function to Node.js via N-API. */
export declare function decode(image: string): Promise<void>
